name: 'Gen Ai Photoshoots Streamlit App Action'
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: List files in current directory
        run: ls

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      
      - name: Install dependencies
        run: poetry install
      
      - name: Test with pytest
        run: pytest --doctest-modules --junitxml=junit/test-results.xml
      
      - name: Lint with flake8
        run: poetry run flake8 --max-line-length=120
