name: 'Gen Ai Photoshoots Streamlit App Action'
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: List files in current directory
        run: ls

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      
      - name: Install dependencies
        run: poetry install
      
      - name: Lint with ruff
        if: ${{ inputs.ruff == 'true' }}
        uses: chartboost/ruff-action@v1
        # TODO: Add ability to define example secrets.toml values for smoke test
      
      - name: Test with pytest
        shell: bash
        run: |
          cp $GITHUB_ACTION_PATH/*.py .
          python -m pytest ${{ inputs.pytest-args }} --junitxml=test-results.xml || echo "No tests found"
        env:
          APP_PATH: ${{ inputs.app-path }}
          SKIP_SMOKE: ${{ inputs.skip-smoke }}
      
      - name: Lint with flake8
        run: poetry run flake8
      
      - name: Deploy Streamlit App
        uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: ${{ inputs.app-path }}
          ruff: ${{ inputs.ruff }}
          pytest-args: ${{ inputs.pytest-args }}
      
      - name: Publish Test Results
        if: always()
        uses: pmeier/pytest-results-action@v0.6.0
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: false
